# Generated by Django 5.2.13 on 2026-05-09 21:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0061_add_record"),
    ]

    operations = [
        migrations.AddField(
            model_name="item",
            name="artist",
            field=models.TextField(blank=True, default=""),
        ),
        migrations.AddField(
            model_name="item",
            name="publisher",
            field=models.TextField(blank=True, default=""),
        ),
        migrations.AddField(
            model_name="item",
            name="year",
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
    ]
