# Generated by Django 5.2.13 on 2026-05-09 22:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0062_item_artist_item_publisher_item_year"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Play",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("artist", models.TextField(blank=True, default="")),
                ("title", models.TextField(blank=True, default="")),
                ("album", models.TextField(blank=True, default="")),
                ("played_at", models.DateTimeField(db_index=True)),
                (
                    "duration_seconds",
                    models.PositiveIntegerField(blank=True, null=True),
                ),
                (
                    "source",
                    models.CharField(
                        choices=[
                            ("manual_vinyl", "Manual Vinyl"),
                            ("listenbrainz", "ListenBrainz"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "side",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("A", "Side A"),
                            ("B", "Side B"),
                            ("full", "Full Listen"),
                        ],
                        default="",
                        max_length=10,
                    ),
                ),
                (
                    "item",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="app.item",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-played_at"],
                "indexes": [
                    models.Index(
                        fields=["user", "-played_at"], name="app_play_user_played_idx"
                    ),
                    models.Index(
                        fields=["item", "-played_at"], name="app_play_item_played_idx"
                    ),
                ],
                "constraints": [
                    models.CheckConstraint(
                        condition=models.Q(
                            ("source__in", ["manual_vinyl", "listenbrainz"])
                        ),
                        name="app_play_source_valid",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(("side__in", ["A", "B", "full", ""])),
                        name="app_play_side_valid",
                    ),
                ],
            },
        ),
    ]
