# Generated by Django 5.2.13 on 2026-05-22 03:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0066_widen_play_side_choices"),
    ]

    operations = [
        migrations.AlterField(
            model_name="track",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
    ]
