# Generated by Django 5.2.13 on 2026-05-24 02:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0068_item_air_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='last_hardcover_sync_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='historicalbook',
            name='last_hardcover_sync_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
