# Generated by Django 5.2.13 on 2026-05-25 15:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0069_book_last_hardcover_sync_at_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="DismissedItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "source",
                    models.CharField(
                        choices=[
                            ("tmdb", "The Movie Database"),
                            ("mal", "MyAnimeList"),
                            ("mangaupdates", "MangaUpdates"),
                            ("igdb", "Internet Game Database"),
                            ("openlibrary", "Open Library"),
                            ("hardcover", "Hardcover"),
                            ("comicvine", "Comic Vine"),
                            ("bgg", "BoardGameGeek"),
                            ("discogs", "Discogs"),
                            ("manual", "Manual"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "media_type",
                    models.CharField(
                        choices=[
                            ("tv", "TV Show"),
                            ("season", "TV Season"),
                            ("episode", "Episode"),
                            ("movie", "Movie"),
                            ("anime", "Anime"),
                            ("manga", "Manga"),
                            ("game", "Game"),
                            ("book", "Book"),
                            ("comic", "Comic"),
                            ("boardgame", "Boardgame"),
                            ("record", "Record"),
                        ],
                        max_length=20,
                    ),
                ),
                ("media_id", models.CharField(max_length=64)),
                ("title", models.CharField(blank=True, default="", max_length=255)),
                ("dismissed_at", models.DateTimeField(auto_now_add=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="dismissed_items",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-dismissed_at"],
                "indexes": [
                    models.Index(
                        fields=["user", "media_type", "source"],
                        name="app_dismissed_filter_idx",
                    )
                ],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("user", "source", "media_type", "media_id"),
                        name="app_dismissed_unique",
                    )
                ],
            },
        ),
    ]
