# Generated by Django 5.2.13 on 2026-05-25 18:27

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0070_dismisseditem"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name="anime",
            index=models.Index(fields=["user", "status"], name="app_anime_user_st_idx"),
        ),
        migrations.AddIndex(
            model_name="anime",
            index=models.Index(
                fields=["user", "progressed_at"], name="app_anime_user_pr_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="basicmedia",
            index=models.Index(
                fields=["user", "status"], name="app_basicmedia_user_st_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="basicmedia",
            index=models.Index(
                fields=["user", "progressed_at"], name="app_basicmedia_user_pr_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="boardgame",
            index=models.Index(
                fields=["user", "status"], name="app_boardgame_user_st_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="boardgame",
            index=models.Index(
                fields=["user", "progressed_at"], name="app_boardgame_user_pr_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="book",
            index=models.Index(fields=["user", "status"], name="app_book_user_st_idx"),
        ),
        migrations.AddIndex(
            model_name="book",
            index=models.Index(
                fields=["user", "progressed_at"], name="app_book_user_pr_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="comic",
            index=models.Index(fields=["user", "status"], name="app_comic_user_st_idx"),
        ),
        migrations.AddIndex(
            model_name="comic",
            index=models.Index(
                fields=["user", "progressed_at"], name="app_comic_user_pr_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="episode",
            index=models.Index(
                fields=["related_season", "end_date"],
                name="app_episode_related_2150d3_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="episode",
            index=models.Index(
                fields=["end_date"], name="app_episode_end_dat_4bbd0a_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="game",
            index=models.Index(fields=["user", "status"], name="app_game_user_st_idx"),
        ),
        migrations.AddIndex(
            model_name="game",
            index=models.Index(
                fields=["user", "progressed_at"], name="app_game_user_pr_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="manga",
            index=models.Index(fields=["user", "status"], name="app_manga_user_st_idx"),
        ),
        migrations.AddIndex(
            model_name="manga",
            index=models.Index(
                fields=["user", "progressed_at"], name="app_manga_user_pr_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="movie",
            index=models.Index(fields=["user", "status"], name="app_movie_user_st_idx"),
        ),
        migrations.AddIndex(
            model_name="movie",
            index=models.Index(
                fields=["user", "progressed_at"], name="app_movie_user_pr_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="record",
            index=models.Index(
                fields=["user", "status"], name="app_record_user_st_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="record",
            index=models.Index(
                fields=["user", "progressed_at"], name="app_record_user_pr_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="season",
            index=models.Index(
                fields=["user", "status"], name="app_season_user_st_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="tv",
            index=models.Index(fields=["user", "status"], name="app_tv_user_st_idx"),
        ),
    ]
