# Generated by Django 5.2.13 on 2026-05-23 15:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('integrations', '0002_webhookevent'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='webhookevent',
            new_name='integration_user_id_b18614_idx',
            old_name='whevent_user_created_idx',
        ),
    ]
