# Generated by Django 5.2.13 on 2026-05-24 02:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0069_book_last_hardcover_sync_at_and_more'),
        ('integrations', '0003_rename_whevent_user_created_idx_integration_user_id_b18614_idx'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='HardcoverBookMapping',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hardcover_book_id', models.PositiveIntegerField()),
                ('hardcover_edition_id', models.PositiveIntegerField(blank=True, null=True)),
                ('match_method', models.CharField(choices=[('direct_id', 'Direct ID'), ('isbn', 'ISBN-13'), ('title_author', 'Title + Author search'), ('manual', 'Manual override')], default='isbn', max_length=16)),
                ('last_verified_at', models.DateTimeField(auto_now=True)),
                ('item', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='hardcover_mapping', to='app.item')),
            ],
        ),
        migrations.CreateModel(
            name='HardcoverIntegration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('api_token', models.TextField()),
                ('hardcover_user_id', models.PositiveIntegerField(blank=True, null=True)),
                ('hardcover_username', models.CharField(blank=True, default='', max_length=255)),
                ('enabled', models.BooleanField(default=True)),
                ('last_pushed_at', models.DateTimeField(blank=True, null=True)),
                ('last_error', models.TextField(blank=True, default='')),
                ('last_error_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='hardcover', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
