# Generated by Django 5.2.13 on 2026-05-27 01:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('integrations', '0005_koreaderbookmapping'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='KOReaderProgressEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('percentage', models.FloatField()),
                ('progress', models.TextField(blank=True, default='', help_text='Opaque KOReader position string at the moment of this push.')),
                ('device', models.CharField(blank=True, default='', max_length=255)),
                ('device_id', models.CharField(blank=True, default='', max_length=64)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('mapping', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='integrations.koreaderbookmapping')),
                ('user', models.ForeignKey(help_text='Denormalised from mapping.user so per-user history queries skip the mapping join (most common read pattern).', on_delete=django.db.models.deletion.CASCADE, related_name='koreader_events', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', '-created_at'], name='integration_user_id_d93bd0_idx'), models.Index(fields=['mapping', '-created_at'], name='integration_mapping_16675e_idx')],
            },
        ),
    ]
