# Generated by Django 5.2.13 on 2026-05-22 02:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0053_add_record_preferences"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="suwayomi_url",
            field=models.URLField(
                blank=True,
                help_text="Base URL of your Suwayomi-Server WebUI (e.g. https://manga.example.com). When set, manga detail pages show a 'Read on Suwayomi' button that opens a global search for the title.",
            ),
        ),
    ]
