# Generated by Django 5.2.13 on 2026-05-22 03:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0054_user_suwayomi_url"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="theme",
            field=models.CharField(
                choices=[
                    ("default", "Default (slate)"),
                    ("dracula", "Dracula"),
                    ("catppuccin-mocha", "Catppuccin Mocha"),
                    ("catppuccin-macchiato", "Catppuccin Macchiato"),
                    ("catppuccin-frappe", "Catppuccin Frappé"),
                    ("nord", "Nord"),
                    ("gruvbox-dark", "Gruvbox Dark"),
                    ("tokyo-night", "Tokyo Night"),
                ],
                default="default",
                help_text="Color theme for the web UI.",
                max_length=32,
            ),
        ),
    ]
