# Generated by Django 5.2.13 on 2026-05-22 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0055_user_theme"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="density",
            field=models.CharField(
                choices=[
                    ("compact", "Compact"),
                    ("comfortable", "Comfortable"),
                    ("cozy", "Cozy"),
                ],
                default="comfortable",
                help_text="Grid / card density for media lists.",
                max_length=16,
            ),
        ),
    ]
