# Generated by Django 5.2.13 on 2026-05-24 20:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0059_user_auto_mark_prior_episodes'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='font',
            field=models.CharField(choices=[('system', 'System default'), ('serif', 'Serif'), ('mono', 'Monospace'), ('rounded', 'Rounded'), ('humanist', 'Humanist'), ('typewriter', 'Typewriter')], default='system', help_text='Font family used throughout the web UI.', max_length=16),
        ),
        migrations.AlterField(
            model_name='user',
            name='theme',
            field=models.CharField(choices=[('default', 'Default (slate)'), ('dracula', 'Dracula'), ('catppuccin-mocha', 'Catppuccin Mocha'), ('catppuccin-macchiato', 'Catppuccin Macchiato'), ('catppuccin-frappe', 'Catppuccin Frappé'), ('catppuccin-latte', 'Catppuccin Latte (light)'), ('nord', 'Nord'), ('gruvbox-dark', 'Gruvbox Dark'), ('tokyo-night', 'Tokyo Night'), ('rose-pine-moon', 'Rosé Pine Moon'), ('monokai-pro', 'Monokai Pro'), ('solarized-dark', 'Solarized Dark'), ('solarized-light', 'Solarized Light'), ('synthwave', 'Synthwave'), ('newsprint', 'Newsprint (sepia)')], default='default', help_text='Color theme for the web UI.', max_length=32),
        ),
    ]
