# Generated by Django 5.2.13 on 2026-05-25 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0060_add_theme_choices_and_font"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="browse_include_non_english",
            field=models.BooleanField(
                default=False,
                help_text="Include movies / TV in non-English original languages on the Browse page. Off by default so the discovery feed isn't dominated by foreign-language titles you can't immediately watch.",
            ),
        ),
    ]
