# Generated by Django 5.2.13 on 2026-05-25 18:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0061_user_browse_include_non_english"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="streaming_providers",
            field=models.TextField(
                blank=True,
                default="",
                help_text="Comma-separated TMDB provider IDs the user subscribes to.",
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="browse_include_non_english",
            field=models.BooleanField(
                default=False,
                help_text="Include Hindi titles on the Browse page. Off by default — Bollywood entries dominate TMDB's 'popular' lists in some regions despite being unwatchable for users who don't speak the language. Field name kept for migration history.",
            ),
        ),
    ]
