# Generated by Django 5.2.13 on 2026-05-26 02:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0071_media_perf_indexes'),
        ('auth', '0012_alter_user_first_name_max_length'),
        ('users', '0062_streaming_providers'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='user',
            name='list_detail_sort_valid',
        ),
        migrations.AlterField(
            model_name='user',
            name='list_detail_sort',
            field=models.CharField(choices=[('date_added', 'Date Added'), ('title', 'Title'), ('media_type', 'Media Type'), ('release_date', 'Release Date')], default='date_added', max_length=20),
        ),
        migrations.AddConstraint(
            model_name='user',
            constraint=models.CheckConstraint(condition=models.Q(('list_detail_sort__in', ['date_added', 'title', 'media_type', 'release_date'])), name='list_detail_sort_valid'),
        ),
    ]
