# Generated by Django 5.2.13 on 2026-05-26 03:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0063_remove_user_list_detail_sort_valid_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PushSubscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('endpoint', models.URLField(help_text='Push service endpoint URL issued by the browser.', max_length=600, unique=True)),
                ('p256dh', models.CharField(help_text='Base64url-encoded public key for payload encryption.', max_length=200)),
                ('auth', models.CharField(help_text='Base64url-encoded auth secret for payload encryption.', max_length=200)),
                ('user_agent', models.CharField(blank=True, max_length=300)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('last_used_at', models.DateTimeField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='push_subscriptions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'constraints': [models.UniqueConstraint(fields=('endpoint',), name='unique_push_endpoint')],
            },
        ),
    ]
