# Generated by Django 5.2.13 on 2026-05-29 04:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0064_pushsubscription"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="eink_mode",
            field=models.CharField(
                choices=[
                    ("off", "Off"),
                    ("auto", "Auto (detect e-ink screens)"),
                    ("on", "Always on"),
                ],
                default="auto",
                help_text="High-contrast e-ink display mode (layers on top of theme).",
                max_length=8,
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="theme",
            field=models.CharField(
                choices=[
                    ("default", "Default (slate)"),
                    ("dracula", "Dracula"),
                    ("catppuccin-mocha", "Catppuccin Mocha"),
                    ("catppuccin-macchiato", "Catppuccin Macchiato"),
                    ("catppuccin-frappe", "Catppuccin Frappé"),
                    ("catppuccin-latte", "Catppuccin Latte (light)"),
                    ("nord", "Nord"),
                    ("gruvbox-dark", "Gruvbox Dark"),
                    ("tokyo-night", "Tokyo Night"),
                    ("rose-pine-moon", "Rosé Pine Moon"),
                    ("monokai-pro", "Monokai Pro"),
                    ("one-dark", "One Dark"),
                    ("everforest", "Everforest"),
                    ("ayu-mirage", "Ayu Mirage"),
                    ("kanagawa", "Kanagawa"),
                    ("solarized-dark", "Solarized Dark"),
                    ("solarized-light", "Solarized Light"),
                    ("synthwave", "Synthwave"),
                    ("newsprint", "Newsprint (sepia)"),
                ],
                default="default",
                help_text="Color theme for the web UI.",
                max_length=32,
            ),
        ),
    ]
