# Generated by Django 5.2.13 on 2026-05-30 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0065_user_eink_mode_alter_user_theme"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="browse_only_my_services",
            field=models.BooleanField(
                default=False,
                help_text="Only show Browse results available on my streaming services.",
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="weekly_recap_enabled",
            field=models.BooleanField(
                default=False, help_text="Send a weekly recap of what you finished."
            ),
        ),
    ]
